### PR TITLE
Update text for OP-TEE security issue 0002 and 0003

### PR DESCRIPTION
**Pull request by jbech-linaro**
Add all details and links to fixes etc, we will get the CVE number when we have provided all this on the public page. Once this has been put on optee.org I will Kurt from Mitre now and then we will get the CVE numbers for it.

Signed-off-by: Joakim Bech <joakim.bech@linaro.org>

### CODE REVIEW

**Comment by shovanuk** [comment]
@jbech-linaro once the pull is accepted, you will see the changed in "Staging" site, we will have to do a manual push to live website. 

https://staging.op-tee.org/security-advisories/

**Comment by jbech-linaro** [comment]
> @jbech-linaro once the pull is accepted, you will see the changed in "Staging" site, we will have to do a manual push to live website.

OK, please just inform me when you have pushed it to the live site, so that I can close the ongoing thread with the ones assigning CVE numbers.

**Comment by shovanuk** [comment]
Hi @jbech-linaro 

The changes have been applied. 
https://www.op-tee.org/security-advisories/

Thanks
Shovan

**Comment by jbech-linaro** [comment]
Thanks Shovan!

**Pull request merged**
