### PR TITLE
GDPR compliant newsletter added - Search updated

### PR DESCRIPTION
**Pull request by kylekirkby**

### CODE REVIEW

**Comment by jbech-linaro** [comment]
A mix of everything. Content wise it looks good, patch wise it doesn't look that nice (lots of different unrelated patches, no-squashed patches etc).

`Acked-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jbech-linaro** [comment]
Btw, how comes it contains a lot of patches already found in the upstream tree?

**Comment by kylekirkby** [comment]
I've pulled the changes from Master this is the Develop branch which builds to staging.op-tee.org

**Comment by jbech-linaro** [comment]
Ah! Didn't pay attention to the branch name, now I get it, thanks!

**Pull request merged**
