### PR TITLE
Re-word index.md

### LINKED ISSUE #118: Wording on index.md could be improved
Examples:
* "ended up"
* Sentence starting with "But before"
* Sentence ending "etc."
* Sentence starting with "A bit"
* The whole sentence starting with "In 2015"
* Another sentence starting with "But for"

I could attempt a rewrite suggestion in a PR, but I'm not a marketing guru. :smiley:

### PR DESCRIPTION
**Pull request by morancj**
Attempt to resolve #118 : please review and comment, or just push changes here. :smiley:

### CODE REVIEW

**Comment by morancj** [comment]
@kylekirkby , please review the YAML and embedded Markdown content. @jbech-linaro can decide if he likes the wording or not.
I have addressed the inconsistent indentation, but not changed the 4 spaces to 2.

**Comment by morancj** [comment]
This PR did not result in a test build to the staging site. I'm unsure if this is a deliberate exception.

**Comment by kylekirkby** [comment]
> This PR did not result in a test build to the staging site. I'm unsure if this is a deliberate exception.

What do you mean the tests appear to have already been executed ?

**Comment by morancj** [comment]
@kylekirkby Never mind, sorry for the noise. I forgot staging doesn't get updated until the merge! :man_facepalming: I will build locally as I should have done in the first place.

**Comment by kylekirkby** [comment]
> @kylekirkby Never mind, sorry for the noise. I forgot staging doesn't get updated until the merge!  I will build locally as I should have done in the first place.

Or you could help push for a preview link feature to be added :+1:

**Comment by morancj** [comment]
Looks OK, not sure about the highlighting I added for `OP-TEE` and `TEE`.

> > @kylekirkby Never mind, sorry for the noise. I forgot staging doesn't get updated until the merge!  I will build locally as I should have done in the first place.
> 
> Or you could help push for a preview link feature to be added +1

Issue link?

**Pull request merged**
